branches:
  only:
    - master
language: node_js
cache:
  bundler: true
  directories:
    - node_modules
node_js:
  - stable
before_install:
  - openssl aes-256-cbc -K $encrypted_15b8f41eeee9_key -iv $encrypted_15b8f41eeee9_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
  # Configure file access permission
  - chmod 600 ~/.ssh/id_rsa
  # Configure ssh
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - cp .travis/ssh_config ~/.ssh/config
  # Congfigure git information
  - git config --global user.name 'Gyumeijie'
  - git config --global user.email '18170879819@163.com'

### Install stage ###
install:
  - echo "install stage"

### Build stage ###
script:
  - echo "build stage"
  - echo $encrypted_15b8f41eeee9_iv
  - echo $encrypted_15b8f41eeee9_key
after_success:
    # Must switch to another branch instead of master 
  - (git pull origin log && git checkout log >&/dev/null) || git checkout -b log >&/dev/null
  - cd logger
  - echo `date +"%Y-%m-%d %H:%M"` >> log
  - git add --all
  - git commit -m "log in `date +"%Y-%m-%d %H:%M"`"
    # Make sure to make the output quiet, or else the API token will leak!
  - git push -f git@github.com:Gyumeijie/travis-ci.TRY.git log
